-- MySQL Script generated by MySQL Workbench
-- mar 04 abr 2017 01:53:56 ART
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema PsicoWebDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PsicoWebDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PsicoWebDB` DEFAULT CHARACTER SET utf8 ;
USE `PsicoWebDB` ;

-- -----------------------------------------------------
-- Table `PsicoWebDB`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PsicoWebDB`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `PsicoWebDB`.`Usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dni` VARCHAR(9) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(60) NOT NULL,
  `mail` VARCHAR(100) NOT NULL,
  `fechaNacimiento` DATE NOT NULL,
  `administrador` BIT(1) NOT NULL DEFAULT 0,
  `password` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PsicoWebDB`.`Turno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PsicoWebDB`.`Turno` ;

CREATE TABLE IF NOT EXISTS `PsicoWebDB`.`Turno` (
  `idTurno` INT NOT NULL AUTO_INCREMENT,
  `dia` DATE NOT NULL,
  `horario` TIME NOT NULL,
  `idUsuario` INT NULL,
  PRIMARY KEY (`idTurno`),
  INDEX `fk_Turno_1_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_Turno_1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `PsicoWebDB`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
